### ISSUE TITLE
Group sources page sorting

### ISSUE THREAD

**Issue by cfremling** [fritz-marshal/fritz#100]
We need the ability to sort by e.g., saved_date on the group sources page, e.g., https://fritz.science/group_sources/41
Some further columns (that are optional in the menu) are also needed for display at the top level, most critical being peak magnitude, current magnitude and when these mags happened, info about if a spectrum exists or not and TNS name. (The basic info needed to determine what should be assigned for spectroscopy, classified, or sent to TNS)

**Comment by dannygoldstein** [comment]
@guynnir42

**Comment by dannygoldstein** [comment]
Assigning @kmshin1397 to this as well pending @guynir42's availability.

**Comment by dannygoldstein** [comment]
(I can't explicitly assign this to @guynir42 until he accepts the invitation to have write access to the repo).

**Comment by kmshin1397** [comment]
^ @cfremling This PR takes care of the sorting on date saved (as well as some of the other columns like redshift). I will start working on the further columns to be added soon.
