### ISSUE TITLE
Headers of spectra in Fritz database

### ISSUE THREAD

**Issue by cfremling** [fritz-marshal/fritz#101]
We need the .fits headers included as comments when downloading spectra of Fritz
This info is critical for various analyses (e.g., plots as a function of exp. time), getting exact JD of middle of exposure, exact instrument setups (gratings, grisms), etc.
While it could be nice to have some of this info properly ingested, it is just as important to have the ability to leave a .fits or .ascii header alone and retain it throughout uploading and later downloading. If I download 1000 spectra next year I want the untouched output files from the SEDM, P200, or whatever pipeline, and not in any way modified from their original state.

**Comment by dannygoldstein** [comment]
Hi @cfremling,

Everything you request here already exists within the `/api/spectrum` endpoint. You can access the ASCII headers in 2 ways. 

Consider, as an example

https://fritz.science/api/spectrum/50

If you hit this endpoint with a `GET` and coerce the output to json, 

```
json = requests.requests('GET', 'https://fritz.science/api/spectrum/50', headers=headers)
```

the original untouched ASCII file that was uploaded is available as  `json['data']['original_file_string']`.

If you want the header already parsed for you, then use `json['data']['altdata']`.
