### ISSUE TITLE
Permission issue to modify observation

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz#126]
Hi,

Mattia Bulla triggered SEDm on ZTF20acuzydz on behalf of the infant-SN group. New observations revealed that the object is bogus. I am part of the infant-SN program and would like to delete the SEDm request. However, I get a permission error. We need is the following: observations triggered on behalf of a program need to be editable by any member of that program. Without that option, we will have situations where we waste precious observing time.

Cheers,

Steve

**Comment by dannygoldstein** [comment]
addressed by https://github.com/skyportal/skyportal/pull/1542
