### ISSUE TITLE
Report "on the TNS" status on the Candidates page

### ISSUE THREAD

**Issue by dmitryduev** [fritz-marshal/fritz#130]
Query K under the hood for fast access to near-real time data.
Should be worked on once the extensions infrastructure is re-worked.

**Comment by dmitryduev** [comment]
@acrellin would you want to take this one on? Should be trivial with what you just implemented.

**Comment by acrellin** [comment]
@dmitryduev Do you envision just adding the TNSInfo component to each candidate row on the scanning page (w/ the requisite redux state structure updates)?

**Comment by dmitryduev** [comment]
Exactly. Just do that asynchronously.

**Comment by acrellin** [comment]
Sure, happy to take this one
