### ISSUE TITLE
Include current redshift in the output from the classifications API query

### ISSUE THREAD

**Issue by dperley** [fritz-marshal/fritz#140]
In order to keep the public BTS webpage up to date and to monitor our classification queue, we must be able to maintain an external database of high-level features of all events in the sample including coordinates, classifications, TNS cross-match IAU IDs, and redshifts.  Currently these can only be retrieved object-by-object by issuing very large numbers of API queries.  Coordinates, TNS IDs, and classifications can now be obtained in relatively short queries that take about 1 second per object and are rarely rejected.  However, redshifts cannot be obtained except with a lengthy query that takes several seconds per event and is prone to being rejected, so there is no straightforward way to keep the redshift database up to date in a timely manner.

To resolve this, I suggest that the current redshift be included in the query to api/sources/ZTFID/classifications.

In the longer term, it may also be worth thinking about making redshifts associated with classifications.  Right now there is no easy way of determining why a redshift was set (based on a NED redshift, from TNS, from a spectrum, etc.)  It would be nice if when entering a classification, one could optionally also enter a redshift alongside it.  This redshift would become the current redshift but would also appear alongside the proposed classification in the classification output in some way.

**Comment by kmshin1397** [comment]
@dperley Have the recent speedups to the sources query satisfied this concern, or would you still like to see redshift information in the classifications API?

**Comment by kmshin1397** [comment]
If so, we can implement an optional flag to include that in the classifications

**Comment by dperley** [comment]
We are now able to pull the redshifts efficiently from the sources table, so there is no longer a need to insert them into the classification API as well - thank you!  If this changes I'll let you know, but for now I'll just close this request.  Thanks for the reminder.
