### ISSUE TITLE
Candidates page: "Show only unsaved candidates" box does not work

### ISSUE THREAD

**Issue by dperley** [fritz-marshal/fritz#145]
**Describe the bug**
On the candidates/scanning page, there is a checkbox to remove candidates already saved to a program.  It does not seem to function: frequently (always?) candidates previously saved to the program still appear.

**To Reproduce**
1. Go to https://fritz.science/candidates
2. Set dates from 2021/01/14 00:00 to 2021/01/15 00:00
3. Select "Show only unsaved candidates"
4. Hit Search
5. Scroll down to see various saved (to RCF) events in the list: for example ZTF20acrseou, ZTF21aabgtar, ZTF20acpjbgc
6. Scroll to the bottom to see that there are 816 candidates total
7. Return to the top of the page, and unselect "Show only unsaved candidates"
8. Hit Search
9. Scroll to the bottom to see that there are 818 candidates total (virtually the same number as above)

(Numbers may vary slightly.)

**Expected behavior**
The intended behavior of this check-box is still not clearly defined to my knowledge, and I am aware of plans to expand the functionality to include options for multi-program scanning.  The way I would like it to function is to hide any events that are saved to the specific program being scanned.  (In almost all cases we do want to see candiates saved to programs _other_ than the one being scanned.)

**Platform information:**
 - Fritz version: v0.9.dev0+git20210113.9d6fe8f+fritz.4d4db0f
 - Interface
   - [ ] I am using the API
   - [X] I am browsing on a desktop
   - [ ] I am browsing on a phone
   - [ ] I am browsing on a tablet

**Comment by Hallflower20** [comment]
Do a hard refresh of the page. They updated it but since browsers cache websites it didn't update. I had the same issue.
