### ISSUE TITLE
Allow users to select which Images they want to see.

### ISSUE THREAD

**Issue by Hallflower20** [fritz-marshal/fritz#146]
**Feature Summary**
On the candidates page you can see 5 images right now. New, Ref, Sub, SDSS, and DR8. On a 1080p monitor this fill the entire width. However, on higher resolution or wider monitors there is just a blank space. If I could select to have PS1 image shown that would be convenient because then I don't have to open the source page to look at it.

**Usage / behavior**
I imagine just having a radio button for each potential image shown. This way you could choose to have any combination, all, or none of the other surveys images.

**Alternative Solutions**
You could just show them all but then it would bad for users with 1080p monitors.

**Additional context**
Demonstration of free space.
![image](https://user-images.githubusercontent.com/40612679/104778333-cd5fd580-5742-11eb-9cca-fdc807207042.png)

**Comment by acrellin** [comment]
Rather than show PS1 thumbnails for all candidates (even optionally), we will likely add a button which will allow users to generate them for specific candidates one at a time (they are very expensive to generate on the backend).

**Comment by acrellin** [comment]
Closing in favor of https://github.com/fritz-marshal/fritz/issues/105
