### ISSUE TITLE
Source Notification did not work

### ISSUE THREAD

**Issue by annayqho** [fritz-marshal/fritz#147]
I tried to issue a source notification (which I think should send an email to everyone in the program). I selected "Fast Transients Partnership" under the Choose Group dropdown menu, selected Soft Alert (email), then "Send Notification"---but no email arrived.

**Comment by acrellin** [comment]
Hi @annayqho , thanks for filing the issue. Can you confirm that expected recipients have enabled email notifications on their profile pages?

**Comment by annayqho** [comment]
Oops, you're right---it was because of that! I'll remind the group to enable notifications. Thanks, and sorry for the trouble.

**Comment by acrellin** [comment]
No worries, and we're glad it's working for you.
