### ISSUE TITLE
WISE links don't work

### ISSUE THREAD

**Issue by dperley** [fritz-marshal/fritz#148]
**Describe the bug**
The links to WISE for each object lead to a page that just displays an error message.

**To Reproduce**
1. Go to any object page
2. Scroll to Surveys
3. Click on WISE
4. The IRSA page pops up an error message that makes it sound like the problem is at their end.  However, if you do a coordinate search of the WISE Image Service (https://irsa.ipac.caltech.edu/applications/wise/) at the same location, the page loads with no issue.  The URL is slightly different than the one that loads from Fritz, making me suspect that the Fritz URL needs to be updated (see below).

**Expected behavior**
Clicking on the WISE link should bring up four-band imaging of the field plus results from a simple catalog search, with no error message.

**Example URLs**

Here is a nonworking URL from the Marshal (specifically https://fritz.science/source/ZTF20acuofwe):
https://irsa.ipac.caltech.edu/applications/wise/#id=Hydra_wise_wise_1&RequestClass=ServerRequest&DoSearch=true&intersect=CENTER&subsize=0.16666666800000002&mcenter=all&schema=allsky-4band&dpLevel=3a&band=1,2,3,4&UserTargetWorldPt=112.3455828;61.4867726;EQ_J2000&SimpleTargetPanel.field.resolvedBy=nedthensimbad&preliminary_data=no&coaddId=&projectId=earchName=wise_1&shortDesc=Position&isBookmarkAble=true&isDrillDownRoot=true&isSearchResult=true

Here is a working URL from doing a search of the WISE image server at the same coordinates:
https://irsa.ipac.caltech.edu/applications/wise/#id=Hydra_wise_wise_1&RequestClass=ServerRequest&DoSearch=true&intersect=CENTER&subsize=0.16666666800000002&mcenter=mcen&schema=allwise-multiband&dpLevel=3a&band=1,2,3,4&UserTargetWorldPt=112.34558333333332;61.48677222222222;EQ_J2000&SimpleTargetPanel.field.resolvedBy=nedthensimbad&preliminary_data=no&coaddId=&projectId=wise&searchName=wise_1&shortDesc=Position&isBookmarkAble=true&isDrillDownRoot=true&isSearchResult=true

I suspect upding the URLs will solve the problem.

**Platform information:**
 - Fritz version: v0.9.dev0+git20210113.9d6fe8f+fritz.4d4db0f
 - Interface
   - [ ] I am using the API
   - [X] I am browsing on a desktop
   - [ ] I am browsing on a phone
   - [ ] I am browsing on a tablet

**Comment by dmitryduev** [comment]
Fixed in https://github.com/skyportal/skyportal/pull/1880, closing.
