### ISSUE TITLE
Capability to check if any source passes a specific filter

### ISSUE THREAD

**Issue by cfremling** [fritz-marshal/fritz#149]
An API endpoint that takes a source or a list of sources, and a filter id (and/or filter version) and outputs if the source(s) passes or fails the particular filter would be extremely useful. This is essential when checking what impact a change to a filter will have on a science program

Similarly a button on the source pages that would call this API for a selected program would be great.

**Comment by dmitryduev** [comment]
Thanks @cfremling. Closing as duplicate of #85.
