### ISSUE TITLE
Propagate Fritz's own and Kowalski's changelog to About in addition to SkyPortal's

### ISSUE THREAD

**Issue by dmitryduev** [fritz-marshal/fritz#151]
**Feature Summary**
We should be propagating Fritz's own and Kowalski's git changelog to the About page in addition to SkyPortal's

**Comment by stefanv** [comment]
Part 1: https://github.com/skyportal/skyportal/pull/1760

**Comment by acrellin** [comment]
@stefanv bump!

**Comment by dmitryduev** [comment]
Implemented, closing.
