### ISSUE TITLE
Public Kafka alert stream

### ISSUE THREAD

**Issue by dmitryduev** [fritz-marshal/fritz#152]
**Feature Summary**
Explore the possibility: a public ZTF Kafka alert stream on the GCP that anyone can connect to (within a reasonable budget).

**Usage / behavior**
Not a db dump, not something where you have to be approved to get access to a down-sized stream, the actual raw Kafka stream so that, e.g. a Kowalski instance can connect to it.

**Implementation details**
See e.g.:
https://www.confluent.io/blog/confluent-cloud-managed-kafka-service-gcp-marketplace/
https://www.confluent.io/confluent-cloud/

**Comment by dmitryduev** [comment]
This is supposed to be a fun exercise!

**Comment by kmshin1397** [comment]
@dmitryduev for this, were you thinking something along the lines of a server set up to listen for the ZTF Kafka stream and then just post some smaller subset of that to its own public Kafka stream so anyone can connect to it? I started reading up on Kafka and trying to get a clearer picture of what this would look like

**Comment by dmitryduev** [comment]
Pretty much. My thinking is:
- A microservice in `kowalski_ingester` similar to `alert_broker_ztf.py` (the microservice must run on a whitelisted IP.), but the only thing it would do would be subscribing to `ztf_%Y%m%d_programid1` topics (i.e. only public data), receiving alerts from those and then simply posting them to an external kafka cluster. I say "simply", but there must be some caveats in this mirroring process. Has this message been processed already? Has it been posted? There must be some ways to do mirroring in a more robust way, need to read up on that.
- That kafka cluster would operate in a minimal vm on the GCP; we would only keep the topics for, say, the last couple night with alert data, to save on storage.
- The latter would be open to the public so that anyone can, for example, spin up Fritz, point its K to it, and immediately start receiving/processing alerts.

**Comment by kmshin1397** [comment]
Looks like there's a standard tool for this so it may be more straightforward than expected: https://docs.confluent.io/4.0.0/multi-dc/mirrormaker.html

**Comment by dmitryduev** [comment]
Closing for now as there is not much interest from the potential users. May reopen in the future.
