### ISSUE TITLE
Filter list

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz#154]
Hi,

I am trying to upload photometry that we obtained with NOT/ALFOSC. Fritz offers only Bessel filters. It would be desirable if users can add filters to upload relevant photometry.

Cheers,

Steve

**Comment by kmshin1397** [comment]
@steveschulze which filters for which instruments are missing that you would like to see added?

**Comment by steveschulze** [comment]
Hi,

I wanted to add SDSS filters to NOT/ALFOSC. Maybe, all instruments should have by default Bessell and Sloan filters, in addition to very specific filters sets, e.g,. UVOT.

I send a pull request some time ago. I don't know why it got stuck. 

https://github.com/skyportal/skyportal/compare/master...steveschulze:master

**Comment by acrellin** [comment]
We have added SDSS filters to ALFOSC
