### ISSUE TITLE
add persistent ZTF-sources with PSF-photometry

### ISSUE THREAD

**Issue by janvanroestel** [fritz-marshal/fritz#155]
To enable variable star science, persistent sources need to be accessible with Fritz. 

**Feature Summary**
persistent sources need to be save-able (they do not have a ZTFyyabcdef ID number). This means that Fritz needs to be able to access the lightcurve database on Kowalski. For ZTF variable sources, all ZTF-PSF (but also alerts) need to be displayed. The most basic method to find variable sources would be to do a cone search, and save a source.

**Usage / behavior**
Example are the ZTF and PTF-variable marshalls. There you can search by Ra & Dec for persistent sources. Once a source is saved, all PSF-photometry is displayed on that page (similar to the alert photometry). 

**Implementation details**
see ZTF variable marshall

**Additional context**
This is the most basic requirement to enable variable science.

**Comment by kmshin1397** [comment]
@dmitryduev Does the recent lightcurve extension stuff cover this issue?

**Comment by dmitryduev** [comment]
Yes @kmshin1397, so closing.
