### ISSUE TITLE
Finding chart generation failed

### ISSUE THREAD

**Issue by yaoyuhan** [fritz-marshal/fritz#156]
**Describe the bug**
For a few sources, the "Finding chart [PDF]" tool fails.
For example:
ZTF21aafnunh
ZTF20acytgxf
ZTF21aadoizf
ZTF20acnviht

**To Reproduce**
1. Go to 'https://fritz.science/source/ZTF20acnviht'
2. Click on 'PDF'
3. finder-chart-pdf.json, Failed - Server problem

**Expected behavior**
Expect to see a pdf of finding chart being downloaded.

**Platform information:**
 - Fritz version: Fritz v0.9.dev0+git20210120.71fddbf+fritz.69d912f.
 - Interface
   - [ ] I am browsing on a desktop

**Comment by dmitryduev** [comment]
@profjsb would you be able to look into this?

**Comment by dannygoldstein** [comment]
This should be fixed by new deploy

________________________________
