### ISSUE TITLE
phase-folding lightcurves

### ISSUE THREAD

**Issue by janvanroestel** [fritz-marshal/fritz#157]
**Feature Summary**
Many variable stars show periodic variability, and it is therefore natural to inspect the phase-folded lightcurve; replace the time axis with an axis that displays the phase.

**Usage / behavior**
The user should be able to input and save a period. (users might not agree on the best period, so multiple periods should be saved and selectable. For a given period, the lightcurve display should display all lightcurves with the phase on the x-axis (instead of time). Note that the different lightcurves should use a common t0. An additional capability would be to 'bin' the phase-folded photometry.

**Implementation details**
Examples can be found in the ZTF and PTF variable marshall. The conversion from time to phase is given by  ([time-t0]/period%1).

**Additional context**

**Comment by dmitryduev** [comment]
Has been implemented, closing.
