### ISSUE TITLE
Show a Gaia HR diagram with the source indicated

### ISSUE THREAD

**Issue by janvanroestel** [fritz-marshal/fritz#159]
For classification of Galactic sources, it's extremely useful to have a HR diagram with the source overplotted.

**Feature Summary**
Automatically generate an HR diagram which shows the source location in the diagram. A background based on a large random sample should be shown for reference. 

**Usage / behavior**
This figure would be added to the overview page (similar to the SDSS cutout, PS cutout etc).

**Implementation details**
This has already been implemented in the labelling interface

**Comment by guynir42** [comment]
@dmitryduev can you get me that PNG with the GAIA data or should we generate one of our own?

**Comment by dmitryduev** [comment]
@guynir42 Here's the png:
https://github.com/dmitryduev/ztf-variable-marshal/blob/master/ztf-variable-marshal/static/img/hr_plot.png
And here's the code to generate the diagram:
https://github.com/dmitryduev/ztf-variable-marshal/blob/master/ztf-variable-marshal/server.py#L1861

**Comment by guynir42** [comment]
@dmitryduev thanks!

**Comment by guynir42** [comment]
Closed by SkyPortal #1726
