### ISSUE TITLE
Stats endpoints/page

### ISSUE THREAD

**Issue by dmitryduev** [fritz-marshal/fritz#162]
Expose information about the current state of the database, such as the number of candidates, sources, photometric points, etc. Also, the number of alerts ingested in the past 24h etc.

**Comment by acrellin** [comment]
@profjsb @stefanv @dmitryduev @kmshin1397 @dannygoldstein @guynir42   Thoughts/additions on data to show here?
Initial thoughts:
 - Counts for most tables (objs, candidates, sources, phtometry, spectra, groups, users, etc)
 - Created time for newest & oldest candidates (to ensure old candidates are being deleted)
 - Number of alerts ingested in the past 24 hrs

**Comment by stefanv** [comment]
It would be handy to know when cron jobs ran and what their exit statuses were, but that would require DB access from the cron runner.

**Comment by acrellin** [comment]
@stefanv some cron jobs (specifically cleaning up old candidates) do already have DB access, so those could log their own activity in a new table before returning

**Comment by acrellin** [comment]
@dmitryduev   When you say "num alerts ingested in past 24 hrs" do you mean querying K for that info, or gleaning that from the SP DB?

**Comment by dmitryduev** [comment]
@acrellin the former. Something like:
![image](https://user-images.githubusercontent.com/7557205/108252837-f0005800-710d-11eb-9583-105609b88c52.png)
(i.e. I'd count from 0h UTC, which would normally give you the number of alerts from a given night)
