### ISSUE TITLE
Forbidden error when attempting to add new instrumnt

### ISSUE THREAD

**Issue by dekishalay** [fritz-marshal/fritz#165]
**Describe the bug**
I'm trying to add a new instrument to the fritz list -- this is an imager called 'Spectral' on the LCO 2m telescope network. I've successfully added the LCO 2m telescope already (telescope_id = 63) but cannot add the instrument

**To Reproduce**
1. Create the LCO instrument JSON 
   lco2m_json = {'name': 'Spectral',
        'type': 'imager',
        'band': 'optical',
        'telescope_id': 63,
        'filters': ['bessellux', 'bessellb', 'bessellv', 'bessellr', 'besselli', 'sdssu', 'sdssg', 'sdssr', 'sdssi', 'sdssz', 'desy']
        }
2. 'POST' the above json to api/instrument with an authorization token. I'm pretty sure my authorization token is correct because the same token allowed me to post the telescope.
3. On trying to post the new instrument, I get {'status': 'error', 'message': 'HTTP 403: Forbidden', 'data': {}, 'version': '0.9.dev0+git20210219.3e00b8a+fritz.eb4bd7d'} -- Is this a permission error?

**Expected behavior**
I expected to get a successful output in the same way I was able to add the LCO 2m telescope network. But it looks like I keep getting a forbidden error -- even though the JSON is pretty similar to the 1m imager already on the fritz instrument list (called 'Sinistro')

**Platform information:**
 - Fritz version: v0.9.dev0+git20210219.3e00b8a+fritz.eb4bd7d
 - Interface
   - I am using the API

**Comment by dannygoldstein** [comment]
Instruments have to be added explicitly by system admins to avoid duplicating instrument records. I just added this.
