### ISSUE TITLE
Change default colors of photometry points from different telescopes/filteres

### ISSUE THREAD

**Issue by katemaguire** [fritz-marshal/fritz#169]
Default colors of displayed photometry are very similar. Fine if approximately same filters have similar colors but SEDM/sdssu and SEDM/sdssr being nearly the same is very difficult to interpret. Also should consider people with color blindness, maybe use different symbols for different telescopes.

<img width="200" alt="Screen Shot 2021-02-24 at 10 48 01" src="https://user-images.githubusercontent.com/9552676/108989742-d753ed00-768d-11eb-890b-9b866fe4939f.png">

**Comment by acrellin** [comment]
Use unique shapes for each instrument/telescope

**Comment by acrellin** [comment]
See color brewer

**Comment by dmitryduev** [comment]
@scizen9 ping

**Comment by scizen9** [comment]
Fixed by [PR#1805](https://github.com/skyportal/skyportal/pull/1805)
