### ISSUE TITLE
Display cross-matches in offset plot

### ISSUE THREAD

**Issue by dmitryduev** [fritz-marshal/fritz#172]
**Feature Summary**
Display cross-matches from multiple catalogs in the offset plot on the Source page.

**Usage / behavior**
The offset plot should display nearest sources from external catalogs stored on Kowalski (including dynamically updated ones such as, e.g. TNS). On hover, display info about the objects, including distance from the centroid position.

**Alternative Solutions**
I would prefer not to do it this way, but: store the cross-match data in altdata. It would have to be kept up-to-date manually for dynamically updated catalogs such as the TNS.

**Implementation details**
- Implement an F-specific endpoint that will query Kowalski for objects from multiple (specified?) catalogs, within a specified distance (up to a reasonable limit), optionally specifying the max number of returned objects per catalog.
  - Define the route in [extensions/skyportal/skyportal/app_server_fritz.py](https://github.com/fritz-marshal/fritz/blob/master/extensions/skyportal/skyportal/app_server_fritz.py)
  - Use [extensions/skyportal/skyportal/handlers/api/kowalski_filter.py](https://github.com/fritz-marshal/fritz/blob/master/extensions/skyportal/skyportal/handlers/api/kowalski_filter.py) as the reference on how to establish connection with F's K and how to query it.
    - It uses the `penquins` library (see [here](https://github.com/dmitryduev/penquins)). Use the `penquins.Kowalski.query` method to call K as in:
```python
response = Kowalski.query(query=query)
data = response.get("data")
```
  - Use the `{"query_type": "near"}` K query type that returns the nearest object(s), sorted by angular distance, in a catalog from a given position. Here's an example query that returns 3 nearest objects in the `milliquas_v6` catalog within 10 degrees from R.A./Decl. = (212.7867456, 59.8409095):
```python
query = {
    "query_type": "near",
    "query": {
        "max_distance": 10,
        "distance_units": "deg",
        "radec": {
            "ZTF20aahgyet": [
                212.7867456,
                59.8409095
            ]
        },
        "catalogs": {
            "milliquas_v6": {
                "filter": {},
                "projection": {
                    "_id": 1,
                    "RA": 1,
                    "DEC": 1
                }
            }
        }
    },
    "kwargs": {
        "limit": 3
    }
}
```
Note that you can specify multiple objects and catalogs in a single query, see the [OpenAPI spec](https://kowalski.caltech.edu/docs/api/#tag/queries).

  - A detailed description on the available K catalogs can be found [here](https://docs.fritz.science/catalogs.html)
  - K's [default config](https://github.com/dmitryduev/kowalski/blob/master/config.defaults.yaml#L196) shows the data we query for and keep when cross-matching the alert stream

**Comment by sjoertvv** [comment]
Just want to mention that for the ZTF TDE working group, this remains our highest priority.
