### ISSUE TITLE
Check for duplicates and duplicate classification

### ISSUE THREAD

**Issue by cfremling** [fritz-marshal/fritz#178]
When RA and DEC is close it would be useful to have a duplicate flag on the source page,
for example https://fritz.science/source/ZTF21aalmkbe is a duplicate of ZTF18aadlaxo
In these cases we run the risk of triggering spectroscopy unnecessarily

We also need a way to classify one of each duplicate as a "duplicate". This is different from the previously mentioned flag, which should also be set when there are two actually different supernovae close to each other.  I suggest adding a duplicate option to the basic taxonomy which we can assign to actual duplicates but not to double supernovae

**Comment by kmshin1397** [comment]
Try out some different small arcsec thresholds

**Comment by acrellin** [comment]
This has been implemented.
