### ISSUE TITLE
API candidate search only returns 25 objects?

### ISSUE THREAD

**Issue by SiPrentice** [fritz-marshal/fritz#181]
**Describe the bug**
I want to use the API to search for candidates between certain dates. When I do this I only ever get 25 results, no matter the values entered for totalMatches, numPerPage, and pageNumber.

**Expected behavior**
From the API docs, my expectation is that I can specify totalMatches, numPerPage, pageNumber to control the amount of candidates saved after StartDate.

**Screenshots**
Below is a screenshot of how I use the API, it shows that I passed totalMatches = '100' and numPerPage = '100' but only got 1 page of 25.

<img width="1112" alt="Screenshot 2021-03-03 at 15 56 09" src="https://user-images.githubusercontent.com/47286009/109833550-43f45c00-7c39-11eb-883d-a7c5c2548ba0.png">

**Platform information:**
 - Fritz version: (find this in the [About](https://fritz.science/about) page)
 - Interface
   - [x ] I am using the API
   - [ ] I am browsing on a desktop
   - [ ] I am browsing on a phone
   - [ ] I am browsing on a tablet

**Comment by stefanv** [comment]
After this is addressed, we should ensure that there is an upper limit (of, say, 100 or 500) and document the limit.

**Comment by acrellin** [comment]
Your query is improperly formatted. Note that query parameters are included in the URL, e.g. `"https://fritz.science/api/candidates?numPerPage=100&pageNumber=1"`
Do not provide a value for `totalMatches`, that is used for internal pagination bookkeeping on the front-end.

**Comment by acrellin** [comment]
Also, `startDate` should not be capitalized, and you should not be putting query parameters in the header -- the authentication token is the only thing you should need to provide to the header

**Comment by acrellin** [comment]
Let us know if you have further questions.
