### ISSUE TITLE
Sort users in User Management

### ISSUE THREAD

**Issue by ivonata** [fritz-marshal/fritz#184]
Please fill out relevant sections below; remove those that are unused.

**Feature Summary**
Sort user in alphabetical order to easily find users. This seems possible from the RCF group but not on the user management tab

**Usage / behavior**
Please describe how this feature should function from a user perspective.

**Alternative Solutions**

**Implementation details**
I wish I did:)

**Additional context**

**Comment by acrellin** [comment]
Hi @ivonata , I believe this is already the case (alphabetized by username) -- what is the ordering that you're seeing?

**Comment by acrellin** [comment]
Also note that you can search by first or last name

**Comment by kmshin1397** [comment]
Just to clarify, the search by name can be accessed through the "Filter Table" tool in the top right of the table

![image](https://user-images.githubusercontent.com/17696889/110143372-2e9c4080-7da5-11eb-92bc-290f580f8d09.png)

**Comment by kmshin1397** [comment]
Closing since filtering already exists and addresses the issue
