### ISSUE TITLE
Interfaces for accessing/working with/displaying external classifications of persistent sources

### ISSUE THREAD

**Issue by dmitryduev** [fritz-marshal/fritz#195]
**Feature Summary**
We need to decide on what the interfaces for accessing/working with/displaying external classifications of persistent sources should look like.

Use cases?

**Usage / behavior**
One option is to store everything on K and pull in data every time it's needed (which works for some use cases, but not for everything).

**Alternative Solutions**
TBD?

**Implementation details**
TBD?

**Comment by guynir42** [comment]
I think it is not just classifications. The classifications is only one aspect of this. 
The HR diagram is a good example. Other people will want to look at other types of data available from cross matches to Gaia etc. 

I think we want to have a subset of the most useful cross matches saved as annotations for all sources where the match exists. 
The users will figure out what is important. 

Then if we feel there is something that needs to be displayed, we will add them in the frontend. 
E.g., classifications from external catalog can show up on the list of classifications, maybe with a different color. 
In this case we can set up a special getter function in one of the handlers to find this info in the annotations for that source.
