### ISSUE TITLE
Unable to generate starlist for observing runs

### ISSUE THREAD

**Issue by Aishwarya113** [fritz-marshal/fritz#196]
Please fill out relevant sections below; remove those that are unused.

**Describe the bug**
I have never been able to generate the starlist on the observing run page. Even after waiting for a long time, given that it can take some time to load, the starlist does not load. I sometimes get an error "Error querying for nearby offset star" right after I select the facility I want to load the starlist for. 

**To Reproduce**
1. Go to 'Observing Runs'
2. Click on 'any observing run'
3. Scroll down to 'facility'
4. Select any facility

**Expected behavior**
This should load a starlist that can be used for the observing run. Ideally this should load the starlist in the format that can the be uploaded to the Palomar computer directly.

**Platform information:**
 - Fritz version: (find this in the [About](https://fritz.science/about) page)
 - Interface
   - [ ] I am using the API
   - [x] I am browsing on a desktop
   - [ ] I am browsing on a phone
   - [ ] I am browsing on a tablet

**Comment by acrellin** [comment]
Unable to reproduce. When viewing a random observing run, the starlists are generated successfully for every possible facility.

**Comment by acrellin** [comment]
@Aishwarya113  Which observing run(s) (IDs) were you experiencing this issue with? Does it persist?

**Comment by Aishwarya113** [comment]
I am not able to generate the starlist for any of the observing runs on fritz. This has been happening since December at least for me. I have never been able to use Fritz to generate the starlist so far.

**Comment by acrellin** [comment]
@Aishwarya113 What browser are you using?

**Comment by Aishwarya113** [comment]
Safari.

**Comment by acrellin** [comment]
@Aishwarya113 can you please try again using either Firefox or Chrome? Safari has some known limitations and we don't officially support it

**Comment by profjsb** [comment]
What groups do you belong to? It's possible that there is a permissions given problem where some sources in the observing run are not observable with your permissions.

**Comment by acrellin** [comment]
@Aishwarya113 Great to hear!
