### ISSUE TITLE
Docs re HR diagrams

### ISSUE THREAD

**Issue by dmitryduev** [fritz-marshal/fritz#197]
**Feature Summary**
We have a "Quick start" section in the docs, now it is time to start writing the "Advanced usage" (or something) section.
Let the first subsection be on adding color info for a source (from a cross-match, for example) that results in an HR diagram being rendered on the Source/Group Sources pages.

**Implementation details**
I'd document this as a case study: show the user how to post an annotation in the proper format using the API and what the rendered results would look like.

**Comment by guynir42** [comment]
closed by skyportal/skyportal#1782
