### ISSUE TITLE
Increase axis label font size for ZTF Vega Plot

### ISSUE THREAD

**Issue by kmshin1397** [fritz-marshal/fritz#22]
I think the y-axis label specifically (the mag) is a little hard to read with the small, bold font. It looks squished to where 'm' and 'a' are almost overlapping (at least on my screen).

![Screenshot 2020-08-29 113150 (2)](https://user-images.githubusercontent.com/17696889/91755950-cca61880-eb80-11ea-8694-7da9cb546431.png)

Should just be a matter of adding a "titleFontSize" to the axis specs. [Docs here](https://vega.github.io/vega-lite/docs/axis.html#title)

**Comment by guynir42** [comment]
Perhaps one of the students wants to take this up?
