### ISSUE TITLE
Replace IPHAS dr2 catalog with IGAPS catalog

### ISSUE THREAD

**Issue by janvanroestel** [fritz-marshal/fritz#224]
IPHAS dr2 has been superseded by the IGAPS catalog and the survey should be updated

**Feature Summary**
The IPHAS dr2 catalog has been superseded by IGAPS (http://www.star.ucl.ac.uk/IGAPS/survey.shtml).  IGAPS included both IPHAS and UVEX; and contains data in the Ugriz-filters. Especially the U-band data is important for compact object science.

**Usage / behavior**
This is simply an update of a catalog available for crossmatching 

**Implementation details**
This is simply an update of a catalog. If needed, some catalog columns can be omitted.

**Additional context**
IGAPS is a Galactic Plane catalog, having this available soon would be nice since the Galactic plane is rising again in the sky

**Comment by dmitryduev** [comment]
Thanks @janvanroestel. Do you want to take a stab at it? You could use @mcoughlin's recent pr on VLASS ingestion https://github.com/dmitryduev/kowalski/pull/92. (Also, this issue should be migrated to K, I think).

**Comment by janvanroestel** [comment]
Yes, I can give it a shot. Yes, this is probably better in the Kowalski repo (I cant seem to transfer it though).

**Comment by dmitryduev** [comment]
Addressed in https://github.com/dmitryduev/kowalski/pull/98, closing.
