### ISSUE TITLE
Retrieve all sources API query not working

### ISSUE THREAD

**Issue by viraj21197** [fritz-marshal/fritz#231]
Please fill out relevant sections below; remove those that are unused.

**Describe the bug**
[Retrieve all sources](https://docs.fritz.science/api.html#tag/sources/paths/~1api~1sources/get) API query is not working. Returns with a 400 Bad Request Error every time. This query with the codes given below was running fine on April 7, 2021

**To Reproduce**
Run the following code:
```
token = 'xx'

def api(method, endpoint, data=None):
    headers = {'Authorization': f'token {token}'}
    response = requests.request(method, endpoint, params=data, headers=headers)
    return response

data = {
    "group_ids" :[43],
    "savedBefore" : '2020-12-21T22:11:25.910271',
    "savedAfter" : '2020-12-19T00:00:00.00',
    "includePhotometry":True
  }

response = api('GET', 'https://fritz.science/api/sources/',data=data)
print(f'HTTP code: {response.status_code}, {response.reason}')

```
The result of the above query is `HTTP code: 400, Bad Request`
**Expected behavior**
I expect the query to run successfully (print '200, Success') and return all sources with program id = 43 that were saved between 2020-12-21 and 2020-12-19.

**Platform information:**
 - Fritz version: v0.9.dev0+git20210412.d4a1595+fritz.3a7b641 (find this in the [About](https://fritz.science/about) page)
 - Interface
   - [x] I am using the API
   - [ ] I am browsing on a desktop
   - [ ] I am browsing on a phone
   - [ ] I am browsing on a tablet

**Additional context**
Running the query with other options also does not work. For example, the following code instead 
```
token = 'xx'

def api(method, endpoint, data=None):
    headers = {'Authorization': f'token {token}'}
    response = requests.request(method, endpoint, params=data, headers=headers)
    return response

data = {
    "ra" : 160.6431061,
    "dec" : 34.4373984,
    "radius":0.0001
  }

response = api('GET', 'https://fritz.science/api/sources/',data=data)
print(f'HTTP code: {response.status_code}, {response.reason}')

```
should return the source [ZTF21aagppzg](https://fritz.science/source/ZTF21aagppzg).

**Comment by acrellin** [comment]
@viraj21197 Can you please also include the error message by showing the contents of `response.json()`?

**Comment by viraj21197** [comment]
Here are the contents of `response.json()`
```
{'status': 'error',
 'message': "'NoneType' object has no attribute 'active'",
 'data': {},
 'version': '0.9.dev0+git20210412.d4a1595+fritz.3a7b641'}
```

**Comment by acrellin** [comment]
Thanks. Fixed by https://github.com/skyportal/skyportal/pull/1871
