### ISSUE TITLE
Source search returning objects with Date Saved date earlier than specified savedAfter date

### ISSUE THREAD

**Issue by SiPrentice** [fritz-marshal/fritz#233]
**Describe the bug**
Using both the API and through Fritz web I find that if I search for objects with _savedAfter_ a particular date, it still returns some objects which were saved before this date. This appears to be a new bug as it has only started happening since the problems of the other day. It may be something you're in the process of sorting.

**To Reproduce**
Do a source search. Select Saved After and some recent date, select all the SNe Ia except Ia-CSM and have a redshift limit of 0.025. See the screenshot below.

**Expected behavior**
The search should only return sources saved after the savedAfter date.

**Screenshots**
<img width="1163" alt="Screenshot 2021-04-13 at 15 43 22" src="https://user-images.githubusercontent.com/47286009/114572778-b3fdf500-9c6f-11eb-8fff-05737abba0f3.png">

**Platform information:**
 - Fritz version: v0.9.dev0+git20210412.3f2ebd0+fritz.e571a27
 - Interface
   - [x] I am using the API
   - [x] I am browsing on a desktop
   - [ ] I am browsing on a phone
   - [ ] I am browsing on a tablet

**Comment by acrellin** [comment]
Thanks @SiPrentice , will be patched later today!

**Comment by SiPrentice** [comment]
Hi,

I see this has been closed but it's still a problem.

<img width="1150" alt="Screenshot 2021-04-19 at 10 31 16" src="https://user-images.githubusercontent.com/47286009/115214914-e2aa1e80-a0fa-11eb-8f00-a198178a9ed9.png">

**Comment by acrellin** [comment]
We've merged the patch, which closed the issue, though we haven't deployed
it to production (this will happen later today). Please do let us know if
it persists after that (we'll let you know when we deploy).

**Comment by acrellin** [comment]
@SiPrentice We've deployed the patch, so please try again and let us know if you encounter any issues.
