### ISSUE TITLE
Group and stream info on Filter page got lost somehow

### ISSUE THREAD

**Issue by dmitryduev** [fritz-marshal/fritz#240]
**Describe the bug**
Filter page should display group and stream info as in (see https://github.com/fritz-marshal/fritz/pull/153)

But this is no longer the case. Investigate and fix.

**Comment by dmitryduev** [comment]
I think it has to do with the new permissioning framework and the fact that the F-specific SP extensions haven't yet been migrated to it.

**Comment by acrellin** [comment]
Fixed by https://github.com/skyportal/skyportal/pull/1909
