### ISSUE TITLE
thumbnails sometimes do not get posted from kowalski

### ISSUE THREAD

**Issue by dannygoldstein** [fritz-marshal/fritz#25]
Logged in as provisioned admin on private.caltech.edu:

<img width="374" alt="Screen Shot 2020-09-01 at 8 09 50 PM" src="https://user-images.githubusercontent.com/2769632/91927739-21d05000-ec8f-11ea-85fd-31a9b9ca0fa7.png">

**Comment by dmitryduev** [comment]
This is fixed, but expect improved robustness in an upcoming pr.
