### ISSUE TITLE
Source search appears not to be working

### ISSUE THREAD

**Issue by SiPrentice** [fritz-marshal/fritz#262]
**Describe the bug**
Since last week, source search has not worked either through the web or via the API. It appears to stall or not complete. 

**To Reproduce**
1) Go to **Sources** in Fritz
2) Filter by some time in early April, max redshift of 0.025, classification = Sitewide Taxonomy: Ia
3) Submit and wait.

**Expected behavior**
Search should return 5 or so sources which fulfil the conditions of the search.

**Screenshots**
This is 5 minutes after submitting the search, nothing has changed on screen.
<img width="1246" alt="Screenshot 2021-05-11 at 09 30 43" src="https://user-images.githubusercontent.com/47286009/117785144-36acac80-b23c-11eb-892c-b00b364f97ad.png">

**Platform information:**
 - Fritz version: (find this in the [About](https://fritz.science/about) page)
 - Interface
   - [x ] I am using the API
   - [x] I am browsing on a desktop
   - [ ] I am browsing on a phone
   - [ ] I am browsing on a tablet

**Comment by SiPrentice** [comment]
An update to this:

I can get the search to work when the classification and savedAfter are specified, but it doesn't work when maxRedshift is specified.

**Comment by acrellin** [comment]
Thanks, we're looking into this.

**Comment by acrellin** [comment]
@SiPrentice We've identified the issue and will deploy the fix later today

**Comment by acrellin** [comment]
@SiPrentice Can you please try again after refreshing the page and let us know whether it's working for you now?

**Comment by SiPrentice** [comment]
Hi, 

Unfortunately it doesn't appear so. Both the search on the webpage and using the API just hangs, the screenshot below is 5 minutes after I submitted a search on Time since 2021-04-02 00:00:00, Sitewide Taxonomy: Ia, and maxRedshift = 0.025

<img width="1411" alt="Screenshot 2021-05-14 at 08 41 42" src="https://user-images.githubusercontent.com/47286009/118238543-8c799280-b490-11eb-9056-feca184f4c79.png">

A search without the redshift condition is slow but works

<img width="1399" alt="Screenshot 2021-05-14 at 08 47 19" src="https://user-images.githubusercontent.com/47286009/118238889-0a3d9e00-b491-11eb-82a3-1be5f5c6ffc9.png">

For the time being I'll incorporate a workaround into our pipeline.

**Comment by acrellin** [comment]
@SiPrentice thanks for the info. We'll address this ASAP.
