### ISSUE TITLE
websockets unresponsive on deployed fritz?

### ISSUE THREAD

**Issue by dannygoldstein** [fritz-marshal/fritz#27]
Sometimes on fritz I lose all connection with the websocket, but don't see any warning notification on the page. Examples (reproducible): 

1. logged in as `provisioned_admin` on private.caltech.edu, on https://private.caltech.edu/share_data/ZTF20abonvte, when I click on points 2862, 2864, 2866, 2880, 2881, and share with Redshift Completeness Factor and Infant SNe, I immediately see a notification that the sharing was successful, but have to reload the page to see the groups updated on the MUI datatable (rather than seeing it immediately update via WS)

2. logged in as `provisioned_admin` on https://private.caltech.edu/source/ZTF20abonvte, when I classify as DM annihilation under sitewide taxonomy 0.1.1 with probabilty 1.0, I immediately see a notification that sharing was successful, but I have to reload the page to see the classification update on the page (rather than seeing it immediately update via WS)

**Comment by dmitryduev** [comment]
Fixed in BL.
