### ISSUE TITLE
More user friendly coordinate search

### ISSUE THREAD

**Issue by janvanroestel** [fritz-marshal/fritz#276]
User indicated that searching for a sources requires many small actions and  streamlining this process is requested

**Feature Summary**
Users have coordinates they want to copy paste to search.

**Usage / behavior**
 Fritz should:

- use a single line for coordinates (instead of 1 for ra and one for dec). This allows a single copy-paste of coordinates
- accept coordinate formats: "ra dec" OR "ra, dec" OR "HHMMSS.S DDMMSS.S" OR "HH:MM:SS.S DD:MM:SS.S"

**alternative solution**

**Implementation details**
some custom python code to check to format and maybe astropy coordinates to transform everything to ra dec in degrees?

**Comment by mcoughlin** [comment]
Closing and opening on SkyPortal: https://github.com/skyportal/skyportal/issues/3123
