### ISSUE TITLE
cannot enter group admins on groups page

### ISSUE THREAD

**Issue by dannygoldstein** [fritz-marshal/fritz#28]
logged in as provisioned_admin, if i go to https://private.caltech.edu/groups

I am unable to enter anything in "Group Admins" (but I can enter things fine into "Group Name")
<img width="1886" alt="Screen Shot 2020-09-01 at 8 30 20 PM" src="https://user-images.githubusercontent.com/2769632/91928870-fc911100-ec91-11ea-97b2-f8f2ba45229f.png">

**Comment by dmitryduev** [comment]
Fixed
