### ISSUE TITLE
Add IRTF SpeX and PGIR to instrument list

### ISSUE THREAD

**Issue by dekishalay** [fritz-marshal/fritz#282]
**Feature Summary**
Please add IRTF+SpeX and Palomar Gattini-IR in list of instruments.

**Usage / behavior**
We would like to upload data from SpeX on IRTF and Gattini-IR. For this, we need the telescope and the instrument in the list of available options at /api/telescope and /api/instrument/

**Implementation details**
And the following instruments in the API for SpeX
{
"api_classname": null,
"telescope_id": 64,
"listener_classname": null,
"type": "imaging spectrograph",
"filters": [
"2massj", "2massh", "2massk"
],
"band": "infrared",
"name": "SpeX",
}

And the following dict for PGIR
{
"api_classname": "PGIRAPI",
"telescope_id": 65,
"listener_classname": null,
"type": "imager",
"filters": [
"2massj"
],
"band": "infrared",
"name": "Gattini-IR",
}

I could not find the 2mass filters in the current filter list -- so those may need to be added as well? We currently envision having a PGIRAPI class as part of PGIR integration although that doesn't exist yet. Thanks!

**Comment by dmitryduev** [comment]
Also need to add PGIR's alert stream.

**Comment by dmitryduev** [comment]
PGIR telescope/instrument/alert stream have been added.

**Comment by guynir42** [comment]
@dekishalay should be easy to do now with new filters!

**Comment by mcoughlin** [comment]
I believe this is now done. Please reopen if there is an issue.
