### ISSUE TITLE
Uptime check on GCP

### ISSUE THREAD

**Issue by dmitryduev** [fritz-marshal/fritz#291]
Essentially, what we do with Runscope, but directly on GCP. We can also hit multiple endpoints (e.g., attempting to get photometry of an old source), not just the sys_info one.

See https://cloud.google.com/monitoring/uptime-checks for details.

**Comment by guynir42** [comment]
@stefanv will lengthen it to 30s intervals and then close this issue.

**Comment by guynir42** [comment]
@stefanv can we close this?
