### ISSUE TITLE
git clone only clones part of the repo

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz#30]
Hi,

I am trying to install Fritz. I pulled the repo with `git clone https://github.com/fritz-marshal/fritz.git && cd fritz`. When I do `pip install -r requirements.txt`, I get the following error:

`ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'kowalski/requirements.txt'`

It turns out that the cloning did not download everything. How can I pull the entire package?

Cheers,

Steve

**Comment by stefanv** [comment]
Hi @steveschulze, thanks for trying Fritz!

The `fritz` tool is the easiest way to deploy.  Run `./fritz --help` for more information.

To pull everything down, including submodules:

```
git submodule update --init
```

**Comment by steveschulze** [comment]
Hi Stefan,

Thanks for your quick reply. This seems to solve some problem. However, there are permission issues.

From the Fritz directory, I do:

`git submodule update --init`

```
Cloning into '/.../ztf-II/fritz/kowalski'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:dmitryduev/kowalski-dev' into submodule path '/.../ztf-II/fritz/kowalski' failed
Failed to clone 'kowalski'. Retry scheduled
Cloning into '/.../ztf-II/fritz/skyportal'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:skyportal/skyportal' into submodule path '/.../ztf-II/fritz/skyportal' failed
Failed to clone 'skyportal'. Retry scheduled
Cloning into '/.../ztf-II/fritz/kowalski'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:dmitryduev/kowalski-dev' into submodule path '/.../ztf-II/fritz/kowalski' failed
Failed to clone 'kowalski' a second time, aborting

```

I already did `rm ~/.ssh/config`, but the error persists.

Cheers,

Steve

**Comment by stefanv** [comment]
Our submodules are set up to be cloned via [SSH keys](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh).

If you don't want to set that up, you can also modify your `~/.gitconfig` to force git it to always use https:

```
[url "https://"]
    insteadOf = git://
```

**Comment by steveschulze** [comment]
Thanks a lot.

Modifying the gitconfig didn't work for me. Setting up the SSH key worked.

**Comment by steveschulze** [comment]
I installed fritz on another computer. This time on a Linux machine instead of a Mac computer. I also set up the SSH key before.

After `git clone https://github.com/fritz-marshal/fritz.git && cd fritz`, I still had to do `git submodule update --init` to clone everything.

Could you add this to the installation instructions and also add a note that an SSH is needed? :)

**Comment by dmitryduev** [comment]
`./fritz run --init` command runs `git submodule update --init --recursive`, see [here](https://github.com/fritz-marshal/fritz/blob/master/fritz#L116), so closing this.
