### ISSUE TITLE
Fritz doesn't show up on localhost:9000 

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz#33]
Hi,

I installed Fritz following all instructions. The unit test worked successfully without any error. Launching Fritz also works, but I can't see the website on `localhost:9000`. Is there a different port of MacOS?

Cheers,

Steve

**Comment by steveschulze** [comment]
Also, on Linux, Fritz doesn't open on `http://localhost:9000/`

**Comment by dmitryduev** [comment]
@steveschulze this is fixed in pr #34, which just got merged. [switched to 5000]
