### ISSUE TITLE
Inaccurate "Hours Below Airmass 2.9" plots on Observability page

### ISSUE THREAD

**Issue by dperley** [fritz-marshal/fritz#333]
**Describe the bug**
The Fritz Observability page for each object now provides a plot of the number of hours the target is observable at night over the course of the year ("Hours Below Airmass 2.9") for each selected observatory.  However, this calculation seems to frequently be inaccurate, even catastrophically inaccurate.  Symptoms include (1) Curves that show an observable object is not observable below airmass 2.9 at any point during the year for some observatories, often in direct contradiction to the accompanying airmass plot; (2) Curves that erratically jump or have sharp bends, which cannot happen given the spherical geometry of the system; (3) Highly dissimilar curves for observatories at similar latitudes.

**To Reproduce**
Go to the Observability tab for any object and view the airmass plots.  A conspicuous example would be: https://fritz.science/observability/ZTF21abowkxx (source coordinates: 14:11:35.67 +07:19:31.2) which shows all three of the symptoms above.  I currently have my airmass plots configured to show Gemini South (30°S), Keck I (20°N), Liverpool Telescope (29°N), Palomar 1.5m (33°N), and VLT (24°S), and for the purposes of this report I also added the Growth India Telescope (32°N).

**Expected behavior**
Seasonal observability curves must be smooth, since the variation over the course of the year is determined by the movement of Sun in the sky.  Furthermore the observability at different sites for the same object should vary only as a function of latitude.  The GROWTH Marshal's observability curve at Palomar for ZTF21abowkxx is below as an example.
![ztf21abowkxx_obs_growth](https://user-images.githubusercontent.com/4943788/129411316-4026f3f8-7022-4a8c-a09a-1223c1328878.png)

**Screenshots**
A screenshot for ZTF21abowkxx is attached.
<img width="1164" alt="ztf21abowkxx_obs_fritz" src="https://user-images.githubusercontent.com/4943788/129411824-48eef09f-83b9-4677-a0c5-9ae9ae55a0db.png">

**Platform information:**
 - Fritz version: v0.9.dev0+git20210813.5fc1f1d+fritz.1f0d49f
 - Interface
   - [ ] I am using the API
   - [x ] I am browsing on a desktop
   - [ ] I am browsing on a phone
   - [ ] I am browsing on a tablet

**Additional context**
This is not a show-stopping bug as the seasonal observability plots are mainly for long-term planning and rarely required for immediate action.  (The airmass plots seem to be OK.)  However, at present the utility of these plots is negated since they cannot currently be trusted.  It is possible some users may be misled.

**Comment by mcoughlin** [comment]
@dperley after the next deployment, see if the above fixed your issue. There was  an issue with the number of hours calculation.
