### ISSUE TITLE
Filtering sources by Last Detected is very slow

### ISSUE THREAD

**Issue by dmitryduev** [fritz-marshal/fritz#338]
We have to check permissions on each photometry point for each source, before deciding whether it's accessible to the user or not, which is extremely slow and has apparently been the cause for the recent intermittent slowdowns.

![image](https://user-images.githubusercontent.com/7557205/130881492-ea569488-1686-4c1c-9f61-d25b3bfa4e9b.png)

I suspect the same will apply to filtering by the Peak magnitude and other quantities associated with the individual photometry points.

For the time being, I suggest to disable it, while we're thinking on the ways to address it properly.

**Comment by mcoughlin** [comment]
Being addressed in SP.
