### ISSUE TITLE
Correct size and orientation of PGIR cutouts

### ISSUE THREAD

**Issue by dekishalay** [fritz-marshal/fritz#339]
**Describe the bug**
Cutouts for PGIR sources are not oriented North Up East Left. Also, the PGIR cutouts have a size of 265" on a side while the current view still uses the ZTF implementation for the archival images (SDSS, PS1, DeCals). 

**To Reproduce**
Go to any PGIR source. The displayed PGIR cutout will be much larger than the archival survey cutouts and the orientation is not North Up East Left. To verify click on any of the archival images (preferably go to SDSS then click the 2MASS button for NIR image) and zoom out to a scale of ~ 5' on a side to get a correct comparison. 

**Expected behavior**
We'd like the PGIR cutouts to be North Up East Left and the archival survey cutouts to be the same size (256").

**Solution**
Change the archival survey cutouts to 256" on a side (or the closest available number). To orient PGIR cutouts correctly, the image needs to be flipped along the x-axis and then rotated 90 degrees clockwise.

**Comment by dmitryduev** [comment]
@dekishalay please add this custom logic here:
https://github.com/dmitryduev/kowalski/blob/master/kowalski/alert_broker.py#L453
(check `if self.instrument == "PGIR":`)

**Comment by dmitryduev** [comment]
Addressed in https://github.com/dmitryduev/kowalski/pull/142, closing.

**Comment by dmitryduev** [comment]
Moved the size part to a separate issue to follow the 1 issue/1 feature(bug) principle.
