### ISSUE TITLE
Spectrum upload permissions error

### ISSUE THREAD

**Issue by dmitryduev** [fritz-marshal/fritz#343]
Reported by Steve Schulze:

**Describe the bug**
"I am trying to upload a spectrum of [ZTF21abzbmhz](https://fritz.science/source/ZTF21abzbmhz). I get a permissions error that I can’t save the spectrum although I am a member of the infant SN group."

"The issue disappears if I associate the spectrum with the “Sitewise” group".

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/7557205/133307827-bf5a8bec-25fb-49c1-92ea-02bca1022adb.png)
![image](https://user-images.githubusercontent.com/7557205/133307873-60fb78a7-4850-4583-ba1d-4aa11c07be3c.png)

**Platform information:**
 - Fritz version: v0.9.dev0+git20210813.f445014+fritz.45d5cba
 - Interface
   - I am browsing on a desktop

**Additional context**
User 26 is actually Josh...

**Comment by steveschulze** [comment]
This error also occurred when I tried to upload all subsequent spectra. As a temporary solution, I shared the spectra with the Sitewise group.

**Comment by steveschulze** [comment]
@dmitryduev, Tawny Sit had the same problem when she tried up upload a DBSP spectrum of the object.

**Comment by dmitryduev** [comment]
@steveschulze so has this only happened to this particular source?

**Comment by steveschulze** [comment]
It's the first time that I saw this error. I don't know whether this would also happen to another source to which user 26 has no access.

**Comment by guynir42** [comment]
Not sure if this is relevant anymore.
