### ISSUE TITLE
Filter/sort (remove irrelevant) annotation origin list.

### ISSUE THREAD

**Issue by jamiesoon** [fritz-marshal/fritz#344]
**Feature Summary**
When scanning for candidates, if you want to filter/sort by any annotation in the drop-down lists, there is a long list of mainly sedm/SN1ascore auto annotations so it is difficult to find the relevant annotation origin.

**Usage / behavior**
Since these seem specific to individual sources due to the subsequent spc notes, either do not show all as default or provide a way to filter these.

**Alternative Solutions**
Saving different filter setups so you only need to use this drop-down once.

**Additional context**
<img width="428" alt="Screen Shot 2021-09-15 at 10 01 53 am" src="https://user-images.githubusercontent.com/26890242/133350566-ece614e4-7722-4b65-8eac-7ce4675f3ec5.png">

**Comment by dmitryduev** [comment]
Thanks @jamiesoon! 

I suggest filtering out entries with `origin in ("sedm", "SNIascore")`. @acrellin should we do this on the front-end or the back-end, what do you think? In either case, this is ZTF-specific, so belongs in this repo.

**Comment by scizen9** [comment]
This will be relieved significantly once spectrum annotations are implemented ([PR #2161](https://github.com/skyportal/skyportal/pull/2161)).  These origins were required to associate them with individual spectra.  I plan to convert all these individual origins to two or three (SNIascore, sedm, SNID?) in total, which will reduce the total number of origins from thousands to tens.

I will update this issue after the PR above is merged and deployed and after I have run a script that will convert all those origins.

**Comment by guynir42** [comment]
@jamiesoon @scizen9 is this issue still relevant? Or has the problem been mostly resolved by moving the annotation unto the spectra?

**Comment by jamiesoon** [comment]
Hi @guynir42,
From a user point of view, this has been mostly resolved as the list is much shorter now.
However, it looks like there are more different types of annotations now so potentially this issue may end up occurring again in the future.
At this point though, my issue has been solved so am happy to close.

**Comment by guynir42** [comment]
Great. Let us know if you run into any trouble with this in the future.
