### ISSUE TITLE
variable star: cannot save sources to group

### ISSUE THREAD

**Issue by janvanroestel** [fritz-marshal/fritz#349]
When I search by coordinates for a variable star, multiple lightcurves were found. However, I cannot save (some) sources to the relevant group.

**Describe the bug**
For some reason, I cannot save some variable stars to my group. In addition, any source that has already been saved also cannot be saved to a new group. They also cannot be found by a search for their name.

**To Reproduce**
1. Go to 'Archive'
2. Search; ZTF_sources_20210401; Ra=13.5014, Dec=14.492, radius=2 and hit search
3. select all lightcurves and try to save temp (save icon on the top-right)
4. A known source should be found (ZTFJ005400.33+142931.4). If you select this source, all group save options are greyed out. It also not possible to go to this sources page to check were it has been saved or get any other information on it.

**Expected behavior**
1) Have a link to the source page if a source has been found when searching by coordinates. and/or give some information to what group this source has been saved to.
2) enable saving the source to another group.

![image](https://user-images.githubusercontent.com/10774087/134589481-23a54438-d6cb-41be-a7a9-4ff21cabf851.png)

**Comment by janvanroestel** [comment]
Hi, I just want to bring this issue to your attention. Not being able to save an already saved source to a different group is a showstopper in the sense that we cannot keep a complete list of a particular type of sources in Fritz. Is any additional information needed for this bug?
- Jan

**Comment by dmitryduev** [comment]
1) #366 makes the existing source(s) clickable (the link will open in new tab/window).
2) You are mixing two operations together - posting photometry to existing sources and saving those existing sources to other groups. The former is performed per ZTF program id (`stream id` on F/SP), so group s don't matter for the purpose of data access. To achieve the latter, go to the object page and click the pencil button (below the Show Starlist button)
![image](https://user-images.githubusercontent.com/7557205/137566130-d5ef237d-9a30-4c59-a7f9-65787a0d789b.png)
