### ISSUE TITLE
Save a period using the Fritz marshall webinterface

### ISSUE THREAD

**Issue by janvanroestel** [fritz-marshal/fritz#364]
Currently, periods can only be saved using an API call. There is strong demand to save a period from the webinterface.

**Feature Summary**
A period and folded lightcurve are both very important for variable star work, and users need to be able to see the folded lightcurves of all bands in the overview page (already implemented). However, users currently need to use an API call to upload a period, and cannot do this from the webinterface. This makes the marshall very inefficient for periodic variable stars (and not useable at all for some users). We, therefore, request the option to save/set/modify the period from the web interface

**Usage / behavior**
Add the capability to save a period. Either 1) a period as provided by the user or 2) the period that comes out of the periodfinding.

**Comment by janvanroestel** [comment]
Can you assign this one to me?

**Comment by guynir42** [comment]
This is addressed by a Skyportal issue https://github.com/skyportal/skyportal/issues/1856
