### ISSUE TITLE
Sphinx requirements cannot be met on own install

### ISSUE THREAD

**Issue by doccosmos** [fritz-marshal/fritz#397]
Following the instructions to install and run my own Fritz, there are missing dependencies in requirements.txt that I needed to additionally install my hand. However, there is also an issue with the version of sphinx required: myst-parser needs a version > 3.1 but it seems other code in fritz needs sphinx < 3. So I'm left with this when trying to init it:

(fritz) [adannu:~/Projects/packages/fritz] mjg% ./fritz run --init
[✓] Initializing submodules
Checking system dependencies:
[✓] python >= 3.7
[✗] docker >= 18.06
[✗] docker-compose >= 1.22.0

[!] Some system dependencies seem to be unsatisfied

    The failed checks were:

    - docker: `docker --version`
      [Errno 2] No such file or directory: 'docker': 'docker'
    - docker-compose: `docker-compose --version`
      [Errno 2] No such file or directory: 'docker-compose': 'docker-compose'

    Please refer to https://docs.fritz.science for installation instructions.

Checking python requirements:
[✓] requests>=2.26
[✓] sphinx_press_theme
[✓] myst-parser
[✓] penquins>=2.1.0
[✓] pyyaml>=5.3.1
[✓] questionary>=1.8.1
[✓] fire>=0.3.1
[✓] pre-commit
[✓] pymongo>=3.10.1
[✓] pyjwt>=2.0.1
[✗] sphinx<3
[✓] deepdiff>=5.0.2
[✓] gsutil>=4.56

[!] Some python package requirements seem to be unsatisfied

    The failed requirements were:

Sphinx 4.4.0 is installed but sphinx<3 is required

    Please refer to https://docs.fritz.science for installation instructions.

Halting because of unsatisfied dependencies.

**Comment by stefanv** [comment]
Do you have an old checkout of skyportal and/or fritz?  We are currently on Sphinx 4.4.

Try:

```
git submodule update --init
```

**Comment by guynir42** [comment]
Still relevant? @doccosmos

**Comment by mcoughlin** [comment]
We can reopen if necessary.
