### ISSUE TITLE
Downloading certain spectra from Fritz loses flux errors and metadata

### ISSUE THREAD

**Issue by tawnysit** [fritz-marshal/fritz#398]
**Describe the bug:**
For certain sources, downloading a spectrum through the Fritz website (Manage Data -> Spectra -> Download) results in a .csv file that contains _only_ the wavelengths and fluxes. Metadata is viewable for these spectra on Fritz via the "Show Altdata" button on the data page and the flux errors are accessible through the API, but these data are not included in the downloaded file.

**Examples of affected sources:**
https://fritz.science/manage_data/ZTF22aacrugz (spec ID 6759)
https://fritz.science/manage_data/ZTF22aaabovk (spec IDs 6414, 6425)

**Expected behavior:**
Spectra downloaded from the Fritz website should include the metadata, wavelengths, fluxes, and flux errors.

**Platform information:**
- Fritz version: v0.9.dev0+git20220303.81741a4b+fritz.0ba47c3
- Interface
   - [x] I am using the API
   - [x] I am browsing on a desktop
   - [ ] I am browsing on a phone
   - [ ] I am browsing on a tablet

**Comment by mcoughlin** [comment]
Closing and opening issue on SkyPortal: https://github.com/skyportal/skyportal/issues/3121
