### ISSUE TITLE
Source page default followup request list order

### ISSUE THREAD

**Issue by cfremling** [fritz-marshal/fritz#415]
**Feature Summary**
We request that the default followup allocation drop-down menu should remember the last selected option and make that the default when a new source page is loaded.

**Usage / behavior**
For example, since I almost always assign allocations on SEDM under the RCF program, a lot of time would be saved if this would be my default selection on the source page.

**Alternative Solutions**
Manual selection of a default/preferred followup request somewhere in the user preferences would also work

**Comment by mcoughlin** [comment]
@cfremling There is a new dropdown in the profile that will appear next deploy. Feel free to reopen if it doesn't meet your needs.
