### ISSUE TITLE
When changing the "Allocation" option under Follow-up, the "Share Data" option should immediately change to the new default 

### ISSUE THREAD

**Issue by dperley** [fritz-marshal/fritz#417]
**Feature Summary**
Currently, when changing the Allocation option under the Follow-up section of a Source page, the "Share Data With" option does not change automatically along with it.  This means that it is very easy to forget and thus have the data be sent to the wrong programme.  As an example, right now the default Follow-up option for me is under "Nuclear Transients", but virtually all of my SEDM triggers are under "Redshift Completeness Factor".  I have to change the option in two places every time, and if I forget the RCF program will not see the data.  (Furthermore, changing the "Share Data With" option is quite tedious becuause it requires scrolling through a very long list of program names.)  To make sure data remains associated with its program of origin, observations triggered under a program should always default to being shared with that program.  So if I change the Allocation option from Nuclear Transients to RCF, the Share Data With option should also change to RCF.

**Usage / behavior**
If the user changes the Allocation option in the dropdown menu, the Share Data option should instantly change to whatever the default is for that program.

**Alternative Solutions**
A different way to implement this would be to _always_ have data triggered under a particular program be shared with the default group for that program, and change "Share Data With" to "Also Share Data With".  While less flexible than the solution above, it could be argued that this is the better solution since it would guarantee that data triggered under a program is always visible to the PI of that program.

Also, if Issue #415 was implemented, this change would be mostly unnecessary for many users: since the vast majority of my triggered follow-up is under the RCF program and if that were simply the default every time, I'd almost never have to change it - this was the case until recently.  (However it would still probably be useful to users who do commonly trigger on different programs, and would help avoid confusion regarding data sharing in the future.)

**Implementation details**
N/A

**Additional context**
A screenshot showing an example of "mismatched" request and data-sharing options is attached.
<img width="601" alt="Screenshot 2022-05-22 at 17 09 47" src="https://user-images.githubusercontent.com/4943788/169704990-e36765d1-2e28-4c07-9a0e-7d28c61827a4.png">

**Comment by mcoughlin** [comment]
@dperley I believe we fixed this in the last deploy, let us know if you see this issue again.
