### ISSUE TITLE
enter specific times for candidates when scanning

### ISSUE THREAD

**Issue by adamamiller** [fritz-marshal/fritz#43]
@acrellin At the moment it's only possible to enter "integer" date ranges when scanning for candidates. 

1. It is not clear whether those times correspond to observation or ingestion (also are they UT, PDT, PST, etc)
2. More importantly - it is important to add more granularity so that it is possible to scan candidates in ~hour long chunks, so specifying hh:mm:ss in addition to the date would be useful.

**Comment by acrellin** [comment]
Addressed in https://github.com/skyportal/skyportal/pull/1009
