### ISSUE TITLE
PGIR filter scanning not working

### ISSUE THREAD

**Issue by dekishalay** [fritz-marshal/fritz#446]
**Describe the bug**
It is not possible to scan for candidates in the PGIR stream anymore. Fritz throws an error when any of the PGIR filters are selected.

**To Reproduce**
1. Go to scanning page
2. Select Palomar Gattini-IR filter (or any filter with PGIR)
3. Click search, and you will see the following error on the top right
<img width="347" alt="Screen Shot 2022-07-11 at 11 10 25 PM" src="https://user-images.githubusercontent.com/33497170/178647616-bb02c870-c676-43ba-9266-559ec8180fb1.png">

**Expected behavior**
The page should display all sources that pass the filter.

**Platform information:**
 - Fritz version: Fritz v0.9.dev0+git20220712.b50e4513+fritz.ad5cbd6
 - Interface
   - I am browsing on a desktop

**Comment by mcoughlin** [comment]
@dekishalay I think this is resolved, reopen as necessary.
