### ISSUE TITLE
Cannot trigger robotic instrument

### ISSUE THREAD

**Issue by erezimm** [fritz-marshal/fritz#448]
Hi,

I get this error when trying to trigger SEDM followup:
"rejected: b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor="white">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n'"

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/53300818/179391173-f53cca9d-3aba-4f07-b649-e5ee9965fc43.png">

This is quite a critical bug for transient catching. Would appreciate if this can be solved quickly.

Thank you!
Erez

**Comment by mcoughlin** [comment]
@erezimm Can you try again now and report back?

**Comment by erezimm** [comment]
Seems like it worked!

Thanks!
Erez

**Comment by mcoughlin** [comment]
Thanks @erezimm .
