### ISSUE TITLE
Add SOAR instruments to instrument list

### ISSUE THREAD

**Issue by dekishalay** [fritz-marshal/fritz#450]
**Feature Summary**
Please add SOAR + Spartan and SOAR + Triplespec in list of instruments.

**Usage / behavior**
We have data and upcoming runs on SOAR, and would like to add instruments to coordinate with Fritz.

**Implementation details**
And the following instruments in the API for SOAR

{'name': 'Spartan',
        'type': 'imager',
        'band': 'infrared',
        'telescope_id': 72,
        'filters': ['2massj', '2massh', '2massks']
  }

{
'name': 'TSpec',
        'type': 'spectrograph',
        'band': 'infrared',
        'telescope_id': 72,
 }

**Comment by mcoughlin** [comment]
@dekishalay Done. Let us know if you see any issues.

**Comment by mcoughlin** [comment]
Done.
