### ISSUE TITLE
Time zone bug in assigning targets to an observing run

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz#452]
Hi,

**Describe the bug**

On 3 August 2022 at 22 o'clock Stockholm (Sweden) time, I tried to assign a target to Christoffer Fremling's Keck run (Hawaii) that started on 3 August. The observing run was shown on https://fritz.science/runs as "one day ago". I couldn't assign any target to it (tested on Chrome and Safari). Christoffer (Caltech) could assign targets to this run. Christoffer played with the local time on his computer. He discovered that the local time is the culprit for an observing run to disappear. 

**Expected behaviour**

Users should be able to assign targets to an observing run before the run starts.

**Comment by mcoughlin** [comment]
@steveschulze I think we got this one in a push earlier this week. Please check again tomorrow post deploy and report back?

**Comment by steveschulze** [comment]
Wow. :) I will check it tomorrow.

**Comment by mcoughlin** [comment]
@steveschulze Let us know and close if it's ok.
