### ISSUE TITLE
False non-detections appear in many objects

### ISSUE THREAD

**Issue by erezimm** [fritz-marshal/fritz#484]
Hi, 

We seem to see many false non-detections in many instances, where there are detections of a transient at the same time as non-detections. for example in [ZTF22abnwpmq](https://fritz.science/source/ZTF22abnwpmq):
![image](https://user-images.githubusercontent.com/53300818/198020561-f7738fe9-b156-4b1a-b7e6-9f93a2105c9b.png)
where a forced photometry pipeline gives:
![image](https://user-images.githubusercontent.com/53300818/198021058-dfcace20-2c47-4d15-8b6f-2ac4d9e4a7fc.png)

I'm not sure if this is a pipeline issue or a fritz issue but i wanted to bring it up here.

Thank you!

Erez

**Comment by mcoughlin** [comment]
We think we got this in the last deploy. Let us know if there are still examples of this.
