### ISSUE TITLE
Wrong time axis on Liverpool Telescope observability plots

### ISSUE THREAD

**Issue by JTerwel** [fritz-marshal/fritz#490]
**Description**
The observability plot for the Liverpool Telescope lists the wrong times

**To Reproduce**
1. Go to https://fritz.science/observability/ZTF22abqxkhd or another object
2. Select Liverpool Telescope & Nordic Optical Telescope
3. Note the differing x-axis while the rest is the same

**Expected behavior**
As the Liverpool Telescope & Nordic Optical Telescope are both on Roque de los Muchachos de La Palma, both plots should be the same. As the sun does not set at 5PM in this time of the year (mid November), it is the Liverpool Telescope whose x-axis is off. Below is a screenshot with an example.

<img width="1151" alt="Screenshot 2022-11-17 at 14 00 54" src="https://user-images.githubusercontent.com/82818204/202466205-80b856c3-0dbc-495b-bf6f-9430b079f659.png">

**Platform information:**
 - Fritz version: v0.9.dev0+git20221116.21fa0401+fritz.bffbd60.
 - Interface
   -  I am browsing on a desktop

**Comment by mcoughlin** [comment]
@JTerwel It looks like LT was put in the wrong place originally. https://fritz.science/telescopes Maybe you @JTerwel or Dan could use the patch API to change the latitude and longitude?

**Comment by mcoughlin** [comment]
@JTerwel 
https://www.youtube.com/watch?v=3qnCT0orKiI&list=PLCRsMmFfImh3SJJOEU8SI2sWrKbV6BnDJ&index=7&ab_channel=SkyPortalAstronomy

The telescope PUT API is here:
https://github.com/skyportal/skyportal/blob/main/skyportal/handlers/api/telescope.py#L221

and the example is here:
https://github.com/skyportal/skyportal/blob/main/skyportal/tests/api/test_telescope.py#L132

**Comment by JTerwel** [comment]
I have tried to change the longitude, but keep getting an authorisation error. What ACL should my token have to be able to do this?

I have Annotate, Classify, Comment, and Upload data. I can make another with Manage observing runs and Run Analyses, but none of these, but I'd have to delete my current one first so I'd like to confirm if this would solve the authorisation access issue first.

**Comment by mcoughlin** [comment]
@JTerwel Please reach out to me on slack to resolve permissions.

**Comment by JTerwel** [comment]
Issue has been fixed. The LT, INT, and WHT are all in their correct location on La Palma
