### ISSUE TITLE
GCN page -  filter sources on rejected tag

### ISSUE THREAD

**Issue by tahumada** [fritz-marshal/fritz#491]
**Feature Summary**
In the GCN page, 'Sources within localization' menu, it would be great if the sources can also be filtered by 'GCN Status' (rejected, confirmed, undefined

**Usage / behavior**
in the search of multi-messenger sources, a lot of sources will be rejected and will be easier to analyze them  if the rejected sources are out of the list
 
**Alternative Solutions**
--
**Implementation details**
--
**Additional context**
--

**Comment by mcoughlin** [comment]
@tahumada I think I merged in the change that you now have a click button to remove rejected sources. It will be deployed today.

**Comment by mcoughlin** [comment]
Please reopen after testing if you decide insufficient.
