### ISSUE TITLE
Submitting filter names in Follow-up request form lead to unexpected results

### ISSUE THREAD

**Issue by Yeqzids** [fritz-marshal/fritz#498]
**Describe the bug**
The pre-filled "filters" box in the Follow-up form under the source page indicates the use of filter names (e.g. r), but entering "r" leads to filter_id=1 (which is g) being used.

**To Reproduce**
1. Go to https://fritz.science/source/ZTs0018
2. Enter "r" in "filters" box under the Follow-up form
3. Submit the request. The ZTF Requests table shows "filters: r", as expected.
4. The executed TOO (in this case, field 611 at around 07:41 UT on 2022-12-22) used g-filter instead. Suspecting that Fritz falls back to filter_id=1 with unexpected input?

**Expected behavior**
TOO request has filters = r or filter_id = 2.

**Screenshots**
n/a

**Platform information:**
 - Fritz version: v0.9.dev0+git20221230.74cd6038+fritz.17a6c53.
 - Interface
   - [ ] I am using the API
   - [x] I am browsing on a desktop
   - [ ] I am browsing on a phone
   - [ ] I am browsing on a tablet

**Additional context**
n/a

**Comment by mcoughlin** [comment]
@Yeqzids Thanks for reporting! I think I figured it out, will go out in deploy tomorrow.
