### ISSUE TITLE
Add Magellan Clay and spectrograph to instrument list 

### ISSUE THREAD

**Issue by dekishalay** [fritz-marshal/fritz#500]
Could you please add the following telescope and instrument. Thanks!
{'name': 'Magellan Clay',
        'nickname': 'Magellan_Clay',
        'diameter': 6.5,
        'robotic': False,
'lat': -29.018,
        'lon': -70.691,
        'elevation': 2380,
        'fixed_location': True
        }

and the imaging spectrograph on Magellan Clay
{'name': 'LDSS-3',
        'type': 'imaging spectrograph',
        'band': 'optical',
        'telescope_id': <fill>,
        }

**Comment by mcoughlin** [comment]
Done.
