### ISSUE TITLE
Reinstigation of the Fritz account expiry date field

### ISSUE THREAD

**Issue by katemaguire** [fritz-marshal/fritz#528]
The ability to update the expiry data of a Fritz account for ZTF data access has been removed. An account has expired and needs to be extended but cannot be.  Urgent since user no longer can access necessary data. [Bug found by Iva Kostadinova - reported on her behalf].

**Comment by mcoughlin** [comment]
@katemaguire The last column of https://fritz.science/user_management has the expiration date, and it looks editable. What is missing exactly?

**Comment by Theodlz** [comment]
Has been fixed since then, closing
