### ISSUE TITLE
Can no longer sort candidates by selected annotation

### ISSUE THREAD

**Issue by jamiesoon** [fritz-marshal/fritz#531]
It used to be possible to sort candidates by clicking on a specific annotation and then "Sort on Selected Annotation".  

**To Reproduce**
1. Go to candidates page
2. Apply a search
3. Click on any annotation
4. "Sort on Selected Annotation" remains greyed out

**Expected behavior**
Sort candidates by clickable annotation.

**Comment by mcoughlin** [comment]
@jamiesoon Can you please post a quick GIF or screenshot to easily identify the issue?

**Comment by jamiesoon** [comment]
![unable_to_sort](https://github.com/fritz-marshal/fritz/assets/26890242/90627d7e-9605-48ff-a03e-04459bef7e0b)
Hopefully, this make it clearer.

**Comment by Theodlz** [comment]
Addressed in https://github.com/skyportal/skyportal/pull/4437, closing (will be redeployed today).
