### ISSUE TITLE
Order annotation sorting alphabetically

### ISSUE THREAD

**Issue by jamiesoon** [fritz-marshal/fritz#532]
**Feature Summary**
On the candidates scanning page, order annotation sorting fields alphabetically. (Annotation Origin, Annotation Key, Annotation Sort Order)

**Usage / behavior**
Instead of the current implementation of an unordered list or ordered by an unknown to the user variable order alphabetically instead.

**Comment by Theodlz** [comment]
Addressed in https://github.com/skyportal/skyportal/pull/4437, closing (will be redeployed today).
