### ISSUE TITLE
Display cross-matched objects from other catalogs on the offset plot

### ISSUE THREAD

**Issue by dmitryduev** [fritz-marshal/fritz#59]
Could either call `/api/alerts/ztf/<objectId>/aux` and grab `cross_matches` from there, or better query K for that specific data (/aux potentially returns a ton of data) on the backend.
Use different markers for different surveys.

**Comment by profjsb** [comment]
Pushing this to SP during candidate save (even if the xmatch wasn't part of the filter), in the form of altdata, seems to make the most sense.

**Comment by dmitryduev** [comment]
@profjsb right. But might need to keep stuff like TNS in sync then.

**Comment by dannygoldstein** [comment]
Duplicate of https://github.com/skyportal/skyportal/issues/1011
