### ISSUE TITLE
add link to ZTF alerts on Source and Candidate pages

### ISSUE THREAD

**Issue by dannygoldstein** [fritz-marshal/fritz#63]
@dmitryduev 

I was about to open a pull request that overrode the source and candidate pages as Fritz extensions with a button that links to the ZTF alerts page. However, I realized that this would cause the Source and Candidates pages in fritz to fall out of sync with what is in SkyPortal. Any ideas on how to override componets that are already in Skyportal with Fritz specific features, but not have the two go out of sync? 

Cc @stefanv

**Comment by dannygoldstein** [comment]
So basically, I was going to copy the current `SourceDesktop.jsx` into `extensions/skyportal/...` then add a ZTF Alerts button to it. 

But I realized this file would soon become stale as it became updated with new features in `skyportal/`, so would require manual re-updating.

**Comment by stefanv** [comment]
This is tricky; I don't see an easy workaround.

You could patch the files in fritz upon deploy, and as long as the patches remain relevant they will apply?

**Comment by kmshin1397** [comment]
@dannygoldstein Any further insights on this? I need to add ZTF alert links to the scanning page.

**Comment by dannygoldstein** [comment]
This should now be possible with the new extensions plan for fritz

**Comment by dmitryduev** [comment]
Implemented, closing.
