### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by dannygoldstein** [fritz-marshal/fritz#67]
Currently the fritz-specific endpoints are not documented.  We should auto-generate API docs for these as we do with the normal skyportal endpoints. Users will make heavy use of many of these endpoints, especially `/api/alerts`. 

This is related to the issue of overriding (rather than introducing totally new) skyportal features that is described in #63.

**Comment by dannygoldstein** [comment]
The new extensions plan should solve this issue. We should start hosting the docs at fritz.science/docs/api

**Comment by dmitryduev** [comment]
This is implemented and lives under https://docs.fritz.science/api.html
