### ISSUE TITLE
Keep preview.fritz.science database relatively up to date with fritz.science database

### ISSUE THREAD

**Issue by dannygoldstein** [fritz-marshal/fritz#93]
The preview.fritz.science database has not received a new source in 18 days. It would be useful for debugging and feature testing purposes to keep realistic data streaming into this DB, so we can better catch bugs before we deploy new versions from staging to production.

**Comment by acrellin** [comment]
@dmitryduev thoughts here?

**Comment by dmitryduev** [comment]
This is not relevant anymore: the staging SP instance has been connected to the staging K instance (and has been receiving nightly data alright), so closing.
