### ISSUE TITLE
filter sources API query by saved_date

### ISSUE THREAD

**Issue by cfremling** [fritz-marshal/fritz#99]
For TNS reporting of new candidates it will save lots of processing time if we can limit the query by saved_date instead of last_detected date in e.g., 'https://fritz.science/api/sources?group_ids=41&startDate=X&endDate=Y'
Currently I cannot query RCF (group 41) without the call timing out in order to later filter by saved_date

**Comment by dannygoldstein** [comment]
@cfremling

We are working on a refactor of the sources handler that should more or less close this issue. 

See https://github.com/skyportal/skyportal/issues/1307

Once that issue is closed, this issue should be closed soon after.

**Comment by dannygoldstein** [comment]
Working up a temporary solution in advance of #1307 which will take longer to merge
